name: defect-gss
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2.6
  - scipy=1.15.2
  - pot=0.9.6
  - matplotlib=3.10.8
  - scikit-image=0.25.2
  - trimesh=4.11.5
  - pytest
  - pip
  - pip:
      - pymeshlab==2025.7.post1
      - -e .
